---
title: "fars_analysis"
author: "Kate Huebner, Maggie Weinroth, Colleen Brent"
date: "10/27/2017"
output:
  word_document: default
  html_document: default
---

```{r global_Options, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE, error = FALSE)
```

```{r}
library(dplyr) 
library(tidyr) 
library(ggplot2)
library(ggthemes)
```

```{r}
load("../data/clean_fars.RData") 
source("../R/fars_functions.R")
dim(clean_fars)
length(unique(clean_fars$unique_id))
summary(clean_fars)

```

```{r}
clean_fars %>%
mutate(year_cat = cut(year, breaks = c(1999, 2002, 2006, 2010),
labels = c("1999-2002", "2003-2006", "2007-2010"),
include.lowest = TRUE, right = TRUE)) %>% filter(!is.na(sex)) %>%
group_by(drug_type, sex, year_cat) %>% summarize(n_non_missing = sum(!is.na(positive_for_drug)),
positive_test = sum(positive_for_drug, na.rm = TRUE),
perc_positive = round(100 * positive_test / n_non_missing, 1)) %>% select(drug_type, sex, year_cat, perc_positive) %>%
unite(sex_year_cat, sex, year_cat) %>%
spread(sex_year_cat, perc_positive) %>%
knitr::kable(col.names = c("Drug type", "F 1999-2002", "F 2003-2006", "F 2007-2010", "M 1999-2002", "M 2003-2006",
                             "M 2007-2010"))
```

```{r, fig.width = 7, fig.height = 4, fig.align ='center'}
#Figure 1: Prevalence of nonalcohol drugs in fatally injured drivers by year and age group
nonalcohol_data <- clean_fars %>%
filter(!drug_type == "Alcohol") %>%
select(unique_id, drug_type, year, agecat, positive_for_drug) %>%
filter(!is.na(positive_for_drug)) %>%
filter(!is.na(agecat)) %>%
group_by(year, agecat, unique_id) %>% 
summarize(positive_for_drug = any(positive_for_drug)) %>% 
ungroup() %>% 
group_by(year, agecat) %>%
summarize(count = 100*(mean(positive_for_drug)))

nonalcohol_data

plot_1 <- nonalcohol_data %>%
ggplot(aes(x = year, y = count, color = agecat)) +
geom_line() +
labs(x = "Year", y = "Positive for Nonalcohol Drugs, %)", color = "Age") +
#scale_y_continuous(limits = c(0,40), breaks = 10, name = "") +
theme_few()
plot_1

```

```{r}
#Figure 2
#Figure 1: Prevalence of nonalcohol drugs in fatally injured drivers by year and age group
data2 <- clean_fars %>%
filter(!drug_type == "Alcohol") %>%
select(unique_id, drug_type, year, agecat, positive_for_drug) %>%
filter(!is.na(positive_for_drug)) %>%
filter(!is.na(agecat)) %>%
group_by(year, drug_type, unique_id) %>% 
summarize(positive_for_drug = any(positive_for_drug)) %>% 
ungroup() %>% 
group_by(year, drug_type) %>%
summarize(count = 100*(mean(positive_for_drug)))

nonalcohol_data

plot_3 <- data2 %>%
ggplot(aes(x = year, y = count, color = drug_type)) +
geom_line() +
labs(x = "Year", y = "Positive for Drugs, %)", color = "Drug type") +
#scale_y_continuous(limits = c(0,40), breaks = 10, name = "") +
theme_few()
plot_3
```


```{r}
#Figure 3
pot_data <- clean_fars %>%
filter(drug_type == "Cannabinoid") %>%
select(unique_id, drug_type, year, agecat, positive_for_drug) %>%
filter(!is.na(positive_for_drug)) %>%
filter(!is.na(agecat)) %>%
group_by(year, agecat, unique_id) %>% 
summarize(positive_for_drug = any(positive_for_drug)) %>% 
ungroup() %>% 
group_by(year, agecat) %>%
summarize(count = 100*(mean(positive_for_drug)))

pot_data

plot_2 <- pot_data %>%
ggplot(aes(x = year, y = count, color = agecat)) +
geom_line() +
labs(x = "Year", y = "Positive for Cannabiniod, %)", color = "Age") +
#scale_y_continuous(limits = c(0,40), breaks = 10, name = "") +
theme_few()
plot_2
```


```{r}
#second function table
drug_list <- c("Alcohol", "Nonalcohol", "Narcotic", "Depressant",
               "Stimulant", "Cannabinoid", "Other")
drug_trend_tests_ca <- lapply(drug_list, test_trend_ca)
drug_trend_tests_ca <- dplyr::bind_rows(drug_trend_tests_ca) %>%
  dplyr::mutate(drug = drug_list) %>%
  dplyr::select(drug, "Z", "p.value")
drug_trend_tests_ca %>%
  knitr::kable(digits = 2)
```

```{r}
#Third function table
drug_list <- c("Alcohol", "Nonalcohol", "Narcotic", "Depressant",
               "Stimulant", "Cannabinoid", "Other")
drug_trend_tests_ca <- lapply(drug_list, test_trend_log_reg)
drug_trend_tests_ca <- dplyr::bind_rows(drug_trend_tests_ca) %>%
  dplyr::mutate(drug = drug_list) %>%
  dplyr::select(drug, "z value", "Pr(>|z|)")
drug_trend_tests_ca %>%
  knitr::kable(digits = 2)

```


